### PR TITLE
Release v2.41.0

### PR DESCRIPTION
**Pull request by jjholmes927**
Release Includes

- Adding POST /verification_details endpoint, which allows integrators to submit creditor based kyc information via the API
- Exposes Scheme idenfitiers for Create/Get/List via the API, and allows scheme Identifiers to be applied to creditors via the `/creditors/:identity/actions/apply_scheme_identifier` route added

### CODE REVIEW

**Comment by hjheath** [comment]
I expected this change to limit the fields you can pass to create creditor. However I don't see those changes.

I wanted us to check that update creditor still supported all the fields even when create creditor does not. Have you built the gem locally and tried using it?

**Comment by jjholmes927** [comment]
@hjheath ahh I think its because your change was merely to remove fields from the public schema, the schema is stored on the template repo to generate the libs themselves but we dont store the schema here. As this is the ruby client lib and there were no types to change etc like on some of the others it makes sense there was no changes to be made to this repo...

I'll test the post creditors endpoint before merging

**Review by hjheath — APPROVED** [review]

**Comment by matthieuprat** [comment]
> I expected this change to limit the fields you can pass to create creditor. However I don't see those changes.

I was surprised by this too but on closer look, it seems we're not performing any kind of client-side validation in the Ruby client so it actually makes sense.

We can see those changes reflected in the .NET client though: https://github.com/gocardless/gocardless-dotnet/commit/0977767d7dc0eff67f17bff189f45d3bdc7d56fd#diff-1efb3ccf421b1fd1ef9d9928fd9db7af9313dc36158192efe8f30c770c775aec

**Comment by jjholmes927** [comment]
Endpoints with creditor schema changes working as expected for both POST and PUT

[POST /creditors](https://kibana.gocardless.io/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30m,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:e9c3c760-638a-11ea-9149-9747a85953a8,key:headers__http_gocardless_client_version,negate:!f,params:(query:'4.21.0'),type:phrase),query:(match_phrase:(headers__http_gocardless_client_version:'4.21.0'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e9c3c760-638a-11ea-9149-9747a85953a8,key:path,negate:!f,params:(query:%2Fenterprise%2Fcreditors),type:phrase),query:(match_phrase:(path:%2Fenterprise%2Fcreditors))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:e9c3c760-638a-11ea-9149-9747a85953a8,key:endpoint_name,negate:!f,params:(query:'Routes::Creditors::Create'),type:phrase),query:(match_phrase:(endpoint_name:'Routes::Creditors::Create')))),index:e9c3c760-638a-11ea-9149-9747a85953a8,interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc))))

[PUT /creditors](https://kibana.gocardless.io/app/kibana#/discover/doc/e9c3c760-638a-11ea-9149-9747a85953a8/logstash-production-2023.01.31?id=NTY3YjRjZGEtYzY4Ny00MTg4LWFkYWItODA3ZmUyMTFlODQz&_g=(filters:!()))

**Pull request merged**
